name: Build Android Kernel

on:
  push: 
  workflow_dispatch:

env:
  CLANG_VERSION: clang-r584948
  CLANG_URL: "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/mirror-goog-main-llvm-toolchain-source/clang-r584948.tar.gz"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          submodules: recursive
    
      - name: Update submodules
        run: git submodule update --remote

      - name: Cache toolchain
        id: toolchain-cache
        uses: actions/cache@v5
        with:
          path: ~/toolchain
          key: toolchain-cache-${{ env.CLANG_VERSION }}

      - name: Get toolchain
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/toolchain
          wget $CLANG_URL
          tar xvf $CLANG_VERSION.tar.gz -C ~/toolchain
          rm $CLANG_VERSION.tar.gz

      - name: Get ccache
        uses: hendrikmuhs/ccache-action@v1.2.23

      - name: Build kernel
        run: |
          set -euo pipefail
          chmod +x ./build.sh
          ./build.sh

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: warn
          path: |
            pack/boot.img
