name: Build Android Kernel

on:
  push: 
  workflow_dispatch:

env:
  AOSP_CLANG: clang-r530567
  # could be main, master or mirror-goog-main-llvm-toolchain-source
  AOSP_BRANCH: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc \
            bison \
            build-essential \
            ccache \
            curl \
            dwarves \
            flex \
            gawk \
            git \
            libelf-dev \
            libssl-dev \
            lz4 \
            rsync \
            unzip \
            xz-utils \
            zip \
            zstd

      - name: Cache toolchain
        id: toolchain-cache
        uses: actions/cache@v5
        with:
          path: ~/toolchain
          key: toolchain-cache-${{ env.AOSP_CLANG }}

      - name: Get toolchain
        if: steps.toolchain-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/toolchain
          cd ~/toolchain
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/$AOSP_BRANCH/$AOSP_CLANG.tar.gz  
          tar xvf $AOSP_CLANG.tar.gz
          rm $AOSP_CLANG.tar.gz

      - name: Build kernel
        run: |
          set -euo pipefail
          chmod +x ./build.sh
          ./build.sh

      - name: Upload kernel artifacts
        uses: actions/upload-artifact@v7
        with:
          archive: false
          if-no-files-found: warn
          path: |
            AnyKernel/*.zip
